In [1]:
%matplotlib inline
import numpy as np
import os, sys

paths = {}
paths['dir'] = os.path.abspath(os.path.dirname(os.path.realpath('__file__')))
paths['TestFile'] = os.path.join(paths['dir'],'our_program.lpf')

sys.path.append(paths['dir'])
import LPFParser as lpfp
from Python.classes import LPFEncoder as lpfe

In [2]:
# General parameters
while True:
    try:
        rowNum = int(input("Enter the number of rows in the plate: "))
        colNum = int(input("Enter the number of columns in the plate: "))
        totalTime = int(input("Enter the total time for the experiment in minutes: "))
        ledsPerWell = int(input("Enter the number of LEDs per well: "))
        if rowNum > 0 and colNum > 0 and totalTime > 0 and ledsPerWell > 0:
            break
        else:
            print("All values must be positive integers. Please enter again.")
    except ValueError:
        print("Invalid input. Please enter positive integers.")
# Device params:
timeStep = 10  # ms
# Compute time array
times = np.arange(0, totalTime * 60 * 1000 + timeStep, timeStep)
dp = {}
dp['channelNum'] = rowNum * colNum * ledsPerWell # TOTAL number of channels
dp['numSteps'] = len(times)
dp['timeStep'] = timeStep


# Initialize LPA_mat
LPA_mat = np.zeros((len(times), rowNum, colNum, ledsPerWell), dtype=np.int16)

# Loop through each well and collect input
for row in range(rowNum):
    for col in range(colNum):
        print(f"\nConfiguring well ({row + 1}, {col + 1}):")

        # Selected LED
        while True:
            try:
                selected_led = int(input(f"Enter the LED index (0-{ledsPerWell - 1}): "))
                if 0 <= selected_led < ledsPerWell:
                    break
                else:
                    print(f"Please enter a valid LED index between 0 and {ledsPerWell - 1}.")
            except ValueError:
                print("Invalid input. Please enter an integer.")

        # Frequency in Hz
        while True:
            try:
                frequency = float(input(f"Enter the frequency in Hz for well ({row + 1}, {col + 1}): "))
                if frequency > 0:
                    break
                else:
                    print("Frequency must be a positive number.")
            except ValueError:
                print("Invalid input. Please enter a number.")

        # High intensity percentage
        while True:
            try:
                high_intensity = int(input(f"Enter the high intensity (percentage of maximum) for well ({row + 1}, {col + 1}): "))
                if 0 <= high_intensity <= 100:
                    break
                else:
                    print("High intensity must be between 0 and 100.")
            except ValueError:
                print("Invalid input. Please enter an integer.")

        # Low intensity percentage
        while True:
            try:
                low_intensity = int(input(f"Enter the low intensity (percentage of maximum) for well ({row + 1}, {col + 1}): "))
                if 0 <= low_intensity <= high_intensity:
                    break
                else:
                    print("Low intensity must be between 0 and High intensity.")
            except ValueError:
                print("Invalid input. Please enter an integer.")

        # Illumination duration in ms
        while True:
            try:
                illumination_dur = int(input(f"Enter the illumination duration in milliseconds for well ({row + 1}, {col + 1}): "))
                if 0 < illumination_dur <= totalTime * 60 * 1000:
                    break
                else:
                    print(f"Duration must be between 0 and {totalTime * 60 * 1000} ms.")
            except ValueError:
                print("Invalid input. Please enter an integer.")

        # Compute period and duration for this well
        period = int(1 / frequency * 1000)  # Convert frequency to period in ms

        for ti, t in enumerate(times):  # Iterate through all timesteps
            if (t % period) < illumination_dur:
                LPA_mat[ti, row, col, selected_led] = int(high_intensity / 100 * 4095)
            else:
                LPA_mat[ti, row, col, selected_led] = int(low_intensity / 100 * 4095)

# Finalize by printing the shape of the generated matrix
print(f"\nLPA_mat generated with shape {LPA_mat.shape}.")
print("Configuration complete.")


Configuring well (1, 1):

Configuring well (1, 2):

Configuring well (1, 3):

Configuring well (1, 4):

Configuring well (1, 5):

Configuring well (1, 6):

Configuring well (2, 1):
Frequency must be a positive number.
Frequency must be a positive number.
Duration must be between 0 and 300000 ms.

Configuring well (2, 2):

Configuring well (2, 3):

Configuring well (2, 4):

Configuring well (2, 5):

Configuring well (2, 6):

Configuring well (3, 1):

Configuring well (3, 2):

Configuring well (3, 3):

Configuring well (3, 4):

Configuring well (3, 5):

Configuring well (3, 6):

Configuring well (4, 1):

Configuring well (4, 2):

Configuring well (4, 3):

Configuring well (4, 4):

Configuring well (4, 5):

Configuring well (4, 6):

LPA_mat generated with shape (30001, 4, 6, 2).
Configuration complete.


In [3]:
import numpy as np

np.savetxt("LPA_mat.csv", LPA_mat.reshape(-1, LPA_mat.shape[-1]), delimiter=",", fmt='%d')
print("Matrix saved to 'LPA_mat.csv'")


Matrix saved to 'LPA_mat.csv'


In [4]:
print(LPA_mat)

[[[[   0 3276]
   [   0 3890]
   [   0 3480]
   [   0 4095]
   [   0 4095]
   [   0 3685]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]

  [[   0    0]
   [   0  368]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]]


 [[[   0 3276]
   [   0 3890]
   [   0 3480]
   [   0 4095]
   [   0 4095]
   [   0 3685]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]]


 [[[   0 3276]
   [   0 3890]
   [   0 3480]
   [   0 4095]
   [   0 4095]
   [   0 3685]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]]

  [[   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
   [   0    0]
 

In [5]:
lpfe.LPFEncoder(LPA_mat, dp, paths['TestFile'])

In [6]:
lpfdata = lpfp.LPFtoArray(paths['TestFile'],rowNum, colNum,ledsPerWell) # Can take some time

Header:
	(1, 48, 10, 30001, 0, 0, 0, 0)
Header Data:
	LPF ver: 1
	Number of channels (total): 48
	Time step: 10 (ms)
	Number of time steps: 30001
Intensity Data:
	Parsed 30001 time points (5.00min)


In [7]:
## Plot the 100ms period (well "0")
wellIndices = [0] # Just the first well
#wellIndices = lpfp.trueIndex(wellIndices, rm) # derandomize
mplargs={'xlim': (0,0.01),
         'chLabels': ["Red", "Green"],
         'ylim': (-800,4200)}
channels = [0,1]
savePath = os.path.join(paths['dir'], 'LPF_plot.png')
lpfp.plotLPFData(lpfdata['data'], channels , wellIndices, rowNum, colNum, savePath, mplargs)

RuntimeError: An error occurred during plotting: 'lw'

        def plotLPFData(data, channels=None, wellIndices=None, rowNum=None, colNum=None, savePath=None, mplargs={}):
            '''Plots LPF data for each channel.
            Inputs:
            data (tuple (len 2)) -- tuple containing x-axis data (time points) and y-axis data (LPF channel intensities)
                Structure is identical to that returned from LPFtoArray, as output['data'].
            channels (list of ints) -- list specifying which channels to plot [default: all]
            wellIndices (list of ints) -- list of indices specifying which wells to plot [default: all]
            rowNum, colNum (int) -- number of rows/cols in the plate. Required for specifying wellIndices. [default: same as data]
            savePath (str) -- full path (including image name and file extension) for saving plot [default: not saved]
            mplargs (dict) -- dict of various matplotlib arguments. Currently supported:
                lw (int) - line width; default: 3
                alpha (float, [0,1]) -- line alpha value; default: 0.6
                chColors (list of valid mpl colors) -- length must be equal to the number of channels plotted;
                    default: colorbrewer2.org colors starting with red, green, blue, purple, orange, yellow
                xlabel (str) -- x-axis label; default: 'Time (min)'
                ylabel (str) -- y-axis label; default: 'Intensity (GS)'
                title (str) -- title label; default: none
                chLabels (list of str) -- alternative labels for the channels, must be in order; default: 'Channel n'
                xlabel_size, ylabel_size, title_size (int) -- text size for labels; default: 16, 16, 20
                ticklabel_size (int) -- text size for tick labels; default: 14
                fontweight (str) -- 'bold' or 'normal' are good, check MPL for full list; default: bold
                xlim, ylim (tuple of 2 ints) -- xrange and yrange for plots; default: full range
                legend_loc (str) -- location of the channel num legend; default: 'best'
            Outputs: Plot of LPF data for selected channels and wells. File is saved if a path is given.'''

            if type(data) is not tuple and type(data) is not list:
                raise TypeError("data must be a list or tuple")
            if len(data) != 2:
                raise IOError("data does not have the correct number of elements")
            if len(data[0]) != np.shape(data[1])[0]:
                raise IOError("Number of timepoints in data[0] != number of intensities in data[1]")
            if channels is not None:
                if type(channels) is not list:
                    raise TypeError("channels must be a list")
                for i in channels:
                    if type(i) is not int:
                        raise TypeError("All elements in channels must be ints.")
            else:
                channels = range(np.shape(data[1])[-1])
            if wellIndices is not None:
                if type(wellIndices) is not list:
                    raise TypeError("wellInedices must be a list")
                for i in wellIndices:
                    if type(i) is not int:
                        raise TypeError("all elements in wellIndices must be ints")
            if rowNum is not None:
                if type(rowNum) is not int:
                    raise TypeError("rowNum must be an int")
            else:
                rowNum = np.shape(data[1])[-3]
            if colNum is not None:
                if type(colNum) is not int:
                    raise TypeError("colNum must be an int")
            else:
                colNum = np.shape(data[1])[-2]
            if wellIndices is None:
                wellIndices = range(rowNum*colNum)
            if type(mplargs) is not dict:
                raise TypeError("mplargs must be a dict")
            if len(mplargs.keys()) != 0:
                for k in mplargs.keys():
                    if k in ['lw', 'ticklabel_size', 'xlabel_size', 'ylabel_size', 'title_size']:
                        if type(mplargs[k]) is not int:
                            raise TypeError("Value corresponding to mplargs key %s must be an int"%k)
                        if mplargs[k] < 0:
                            raise IOError("Text and line width sizes must be positive.")
                    elif k in ['alpha']:
                        if type(mplargs[k]) is not float:
                            raise TypeError("Value corresponding to mplargs key %s must be a float"%k)
                        if mplargs[k] < 0 or mplargs[k] > 1:
                            raise IOError("alpha values must be in the range [0,1])")
                    elif k in ['xlabel', 'ylabel', 'title', 'fontweight', 'legend_loc']:
                        if type(mplargs[k]) is not str:
                            if k == 'legend_loc' and mplargs[k] is not None:
                                raise TypeError("Value corresponding to mplargs key %s must be a string"%k)
                    elif k in ['chColors', 'chLabels']:
                        if type(mplargs[k]) is not list:
                            raise TypeError("Value corresponding to mplargs key %s must be a list"%k)
                    elif k in ['xlim', 'ylim']:
                        if type(mplargs[k]) is not tuple:
                            raise TypeError("xlim & ylim args must be tuples")
                    else:
                        raise KeyError("Invlid key given to mplargs -- arg not supported: %s"%k)
            # Default mpl args [colors from colorbrewer2.org]
            default_mplargs = {
                'lw': 3,
                'alpha': 1.0,
                'chColors': ['#e41a1c', '#4daf4a', '#377eb8', '#984ea3', '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999'],
                'xlabel': 'Time (min)',
                'ylabel': 'Intensity (GS)',
                'title': '',
                'chLabels': ['Channel %d'%i for i in channels],
                'xlabel_size': 16,
                'ylabel_size': 16,
                'title_size': 20,
                'ticklabel_size': 14,
                'fontweight': 'bold',
                'xlim': None,
                'ylim': None,
                'legend_loc': 'best'}
            for defk in default_mplargs.keys():
                if defk not in mplargs.keys(): # Need to set default value
                    mplargs[defk] = default_mplargs[defk]

 def plotLPFData(data, channels=None, wellIndices=None, rowNum=4, colNum=6, savePath=None, mplargs=None):
            try:
                # Debugging: Print the shape of data[1]
                print(f"Shape of data[1]: {data[1].shape}")

                # Loop through selected wells and channels
                first = True
                for welli in wellIndices:
                    rcIndices = generate_well_indices(rowNum,
                                                      colNum)  # Assuming this function generates (row, col) indices
                    r, c = rcIndices[welli]  # Get row and column indices for the well

                    for chi in range(len(channels or mplargs['chLabels'])):
                        # Ensure that indices are valid for the data array shape
                        if data[1].ndim == 4 and chi < data[1].shape[3]:  # Check number of dimensions and valid chi
                            plt.step(data[0] / 1000. / 60., data[1][:, r, c, chi],
                                     lw=mplargs['lw'], alpha=mplargs['alpha'],
                                     color=mplargs['chColors'][chi], label=mplargs['chLabels'][chi] if first else None,
                                     where='post')
                        else:
                            msg = f"Invalid indexing with r={r}, c={c}, chi={chi} for data[1] with shape {data[1].shape}."
                            print(msg)
                            raise IndexError(msg)

                        first = False

                # Finalize the plot
                plt.ylim(mplargs['ylim'])
                plt.legend()
                if savePath:
                    plt.savefig(savePath)
                plt.show()
